# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/104i94eTO5uH5dDe1o3uyIs9zIiI9wiW8
"""

# Maseeng J. Masitha
# 28 January 2020
# Python 3.4
# Lab 2

def feelTemp(Temp):                 # Defining the function, feelTemp. Temp is the argument or parameter.
  if Temp >= 100:                   # Condition 1.
    print("It is hot.")             # Result 1.
  elif Temp > 70 and Temp < 100:    # Condition 2.
    print("It is warm.")            # Result 2, and so forth.
  elif Temp > 32 and Temp < 70:
    print("It is cool.")
  else:
    print("It is cold.")

feelTemp(18)                        # Calling on the function.

# Topic: Alternative and chained conditionals
# Multiple conditions for temperature called for elif and else statements always preserving the else statement for the last condition.
# Logical operator, and was used thus creating a boolean expression.
